//! Cross-validation against **Sage** as an independent oracle.
//!
//! The fixture is generated by `scripts/gen_sage_oracle.sage` (committed, so
//! these tests need no Sage installed) and contains values Sage computed with
//! its own algorithms: Kostka numbers as semistandard-tableau counts, symmetric
//! group characters, Schur products (hence every LR coefficient), the four
//! conversions out of the Schur basis, and skew Schur functions.
//!
//! Regenerate with:
//!   sage scripts/gen_sage_oracle.sage > tests/fixtures/sage_oracle.txt

use std::collections::BTreeMap;
use symfn::{
    character, kostka, skew_schur, Elementary, FromSchur, Homogeneous, Monomial, Partition,
    PowerSum, Rational, Ring, Schur, SymFn,
};

const FIXTURE: &str = include_str!("fixtures/sage_oracle.txt");

fn parse_partition(s: &str) -> Partition {
    if s.is_empty() {
        return Partition::default();
    }
    Partition::new(s.split(',').map(|x| x.parse::<u32>().expect("part")))
}

/// Parse `PART:COEFF ...` where COEFF is `n` or `n/d`.
fn parse_expansion(rest: &str) -> Vec<(Partition, (i128, i128))> {
    rest.split_whitespace()
        .map(|tok| {
            let (part, coeff) = tok.rsplit_once(':').expect("PART:COEFF");
            let c = match coeff.split_once('/') {
                Some((n, d)) => (n.parse().expect("num"), d.parse().expect("den")),
                None => (coeff.parse().expect("int"), 1),
            };
            (parse_partition(part), c)
        })
        .collect()
}

/// Iterate `(tag, arg, rest)` over fixture lines.
fn lines() -> impl Iterator<Item = (&'static str, &'static str, &'static str)> {
    FIXTURE.lines().filter(|l| !l.trim().is_empty()).map(|l| {
        let mut it = l.splitn(3, ' ');
        let tag = it.next().unwrap();
        let arg = it.next().unwrap_or("");
        let rest = it.next().unwrap_or("");
        (tag, arg, rest)
    })
}

fn pair(arg: &str) -> (Partition, Partition) {
    let (a, b) = arg.split_once('|').expect("LAM|MU");
    (parse_partition(a), parse_partition(b))
}

/// Compare an integral expansion against the oracle's expected terms.
fn assert_terms<S: SymFn<i64>>(actual: &S, expected: &[(Partition, (i128, i128))], what: &str) {
    let want: BTreeMap<Partition, i64> = expected
        .iter()
        .map(|(p, (n, d))| {
            assert_eq!(*d, 1, "{what}: expected integral coefficient");
            (p.clone(), *n as i64)
        })
        .collect();
    let got: BTreeMap<Partition, i64> =
        actual.terms().iter().map(|(p, c)| (p.clone(), *c)).collect();
    assert_eq!(got, want, "{what}");
}

#[test]
fn kostka_numbers_match_sage() {
    let mut n = 0;
    for (tag, arg, rest) in lines() {
        if tag != "kostka" {
            continue;
        }
        let (lam, mu) = pair(arg);
        let want: u128 = rest.trim().parse().expect("kostka value");
        assert_eq!(kostka(&lam, &mu), want, "K_{{{lam},{mu}}}");
        n += 1;
    }
    assert!(n > 100, "expected a real sweep, got {n}");
}

#[test]
fn characters_match_sage() {
    let mut n = 0;
    for (tag, arg, rest) in lines() {
        if tag != "char" {
            continue;
        }
        let (lam, mu) = pair(arg);
        let want: i128 = rest.trim().parse().expect("character value");
        assert_eq!(character(&lam, &mu), want, "chi^{lam}({mu})");
        n += 1;
    }
    assert!(n > 100, "expected a real sweep, got {n}");
}

#[test]
fn schur_products_match_sage() {
    let mut n = 0;
    for (tag, arg, rest) in lines() {
        if tag != "smul" {
            continue;
        }
        let (mu, nu) = pair(arg);
        let a: Schur<i64> = Schur::monomial(mu.clone(), 1);
        let b: Schur<i64> = Schur::monomial(nu.clone(), 1);
        assert_terms(&a.mul(&b), &parse_expansion(rest), &format!("s{mu}*s{nu}"));
        n += 1;
    }
    assert!(n > 50, "expected a real sweep, got {n}");
}

#[test]
fn integral_conversions_match_sage() {
    let mut n = 0;
    for (tag, arg, rest) in lines() {
        if !matches!(tag, "s2h" | "s2e" | "s2m") {
            continue;
        }
        let lam = parse_partition(arg);
        let s: Schur<i64> = Schur::monomial(lam.clone(), 1);
        let expected = parse_expansion(rest);
        match tag {
            "s2h" => assert_terms(&Homogeneous::from_schur(&s), &expected, &format!("h(s{lam})")),
            "s2e" => assert_terms(&Elementary::from_schur(&s), &expected, &format!("e(s{lam})")),
            "s2m" => assert_terms(&Monomial::from_schur(&s), &expected, &format!("m(s{lam})")),
            _ => continue,
        }
        n += 1;
    }
    assert!(n > 30, "expected a real sweep, got {n}");
}

#[test]
fn power_sum_conversion_matches_sage() {
    let mut n = 0;
    for (tag, arg, rest) in lines() {
        if tag != "s2p" {
            continue;
        }
        let lam = parse_partition(arg);
        let s: Schur<Rational> = Schur::monomial(lam.clone(), Rational::one());
        let got: PowerSum<Rational> = PowerSum::from_schur(&s);

        let want: BTreeMap<Partition, Rational> = parse_expansion(rest)
            .into_iter()
            .map(|(p, (num, den))| (p, Rational::new(num, den)))
            .collect();
        let actual: BTreeMap<Partition, Rational> =
            got.terms().iter().map(|(p, c)| (p.clone(), *c)).collect();
        assert_eq!(actual, want, "p(s{lam})");
        n += 1;
    }
    assert!(n > 10, "expected a real sweep, got {n}");
}

#[test]
fn skew_schur_matches_sage() {
    let mut n = 0;
    for (tag, arg, rest) in lines() {
        if tag != "skew" {
            continue;
        }
        let (lam, mu) = pair(arg);
        let sk: Schur<i64> = skew_schur(&lam, &mu);
        assert_terms(&sk, &parse_expansion(rest), &format!("s_{{{lam}/{mu}}}"));
        n += 1;
    }
    assert!(n > 20, "expected a real sweep, got {n}");
}

#[test]
fn plethysm_matches_sage() {
    use symfn::plethysm;
    let mut n = 0;
    for (tag, arg, rest) in lines() {
        if tag != "pleth" {
            continue;
        }
        let (f, g) = pair(arg);
        let sf: Schur<Rational> = Schur::monomial(f.clone(), Rational::one());
        let sg: Schur<Rational> = Schur::monomial(g.clone(), Rational::one());
        let got = plethysm(&sf, &sg);

        let want: BTreeMap<Partition, Rational> = parse_expansion(rest)
            .into_iter()
            .map(|(p, (num, den))| (p, Rational::new(num, den)))
            .collect();
        let actual: BTreeMap<Partition, Rational> =
            got.terms().iter().map(|(p, c)| (p.clone(), *c)).collect();
        assert_eq!(actual, want, "s{f}[s{g}]");
        n += 1;
    }
    assert!(n >= 20, "expected a real sweep, got {n}");
}
