//! Cross-validation against **Sage** as an independent oracle.
//!
//! The fixture is generated by `scripts/gen_sage_oracle.sage` (committed, so
//! these tests need no Sage installed) and contains values Sage computed with
//! its own algorithms:
//!
//! * the classical layer — Kostka numbers as semistandard-tableau counts,
//!   symmetric group characters, Schur products (hence every LR coefficient),
//!   the four conversions out of the Schur basis, skew Schur functions and
//!   plethysms;
//! * Jack `P` and `J`, in the monomial and power-sum bases;
//! * the `(q,t)` layer — Hall–Littlewood `Q'` and `P`, Kostka–Foulkes, the
//!   `(q,t)`-Kostka table, `H̃`, `∇e_n`, and Macdonald `P`, `Q` and `J`;
//! * every **inverse** expansion — an element written back in a parametric
//!   basis rather than out of one: `s → P` and `s → Q'`, `s → H̃`, `s → J`,
//!   `m → P` and `m → Q`, and the three Jack ones. Sage reaches each by
//!   inverting or solving its own transition matrix where symfn
//!   back-substitutes through its own forward expansion, so agreement is what
//!   holds an inverse to something other than the expansion it came from —
//!   which the in-tree round trips cannot, being blind to any error the
//!   forward direction shares;
//! * the Kronecker product, and the three LLT ribbon dictionaries;
//! * the Hopf structure — coproduct, antipode and counit — and the two
//!   principal specializations with the dimension `f^λ`.
//!
//! Each family is the *offline* half of its oracle: the `scripts/check_*.py`
//! harnesses run wider, and these run on every `cargo test`. Where a family has
//! rival normalizations in circulation the fixture is chosen to tell them
//! apart, so it doubles as the convention pin — the `⚠️` notes below say which
//! swap each case would catch.
//!
//! Regenerate with:
//!   SAGE_DISABLE_SYMFN=1 sage scripts/gen_sage_oracle.sage > tests/fixtures/sage_oracle.txt
//!
//! ⚠️ The environment variable is not optional and the generator refuses
//! without it: Sage reaches this library through its optional backend, so a
//! fixture taken with it enabled is symfn quoting itself
//! (`docs/policies/validation.md`, V3).

use std::collections::BTreeMap;
use symfn::{
    antipode, character, coproduct, counit, dimension, hall_littlewood, hall_littlewood_p, kostka,
    kostka_foulkes, kronecker, macdonald_ht, nabla_e, principal_specialization,
    principal_specialization_q, qt_kostka, schur_to_hall_littlewood_p, schur_to_hall_littlewood_qp,
    skew_schur, Elementary, FromSchur, Homogeneous, Monomial, Partition, PowerSum, QtPoly,
    Rational, Ring, Schur, SymFn,
};

const FIXTURE: &str = include_str!("fixtures/sage_oracle.txt");

fn parse_partition(s: &str) -> Partition {
    if s.is_empty() {
        return Partition::default();
    }
    Partition::new(s.split(',').map(|x| x.parse::<u32>().expect("part")))
}

/// Parse `PART:COEFF ...` where COEFF is `n` or `n/d`.
fn parse_expansion(rest: &str) -> Vec<(Partition, (i128, i128))> {
    rest.split_whitespace()
        .map(|tok| {
            let (part, coeff) = tok.rsplit_once(':').expect("PART:COEFF");
            let c = match coeff.split_once('/') {
                Some((n, d)) => (n.parse().expect("num"), d.parse().expect("den")),
                None => (coeff.parse().expect("int"), 1),
            };
            (parse_partition(part), c)
        })
        .collect()
}

/// Iterate `(tag, arg, rest)` over fixture lines.
fn lines() -> impl Iterator<Item = (&'static str, &'static str, &'static str)> {
    FIXTURE.lines().filter(|l| !l.trim().is_empty()).map(|l| {
        let mut it = l.splitn(3, ' ');
        let tag = it.next().unwrap();
        let arg = it.next().unwrap_or("");
        let rest = it.next().unwrap_or("");
        (tag, arg, rest)
    })
}

fn pair(arg: &str) -> (Partition, Partition) {
    let (a, b) = arg.split_once('|').expect("LAM|MU");
    (parse_partition(a), parse_partition(b))
}

/// Compare an integral expansion against the oracle's expected terms.
fn assert_terms<S: SymFn<i64>>(actual: &S, expected: &[(Partition, (i128, i128))], what: &str) {
    let want: BTreeMap<Partition, i64> = expected
        .iter()
        .map(|(p, (n, d))| {
            assert_eq!(*d, 1, "{what}: expected integral coefficient");
            (p.clone(), *n as i64)
        })
        .collect();
    let got: BTreeMap<Partition, i64> = actual
        .terms()
        .iter()
        .map(|(p, c)| (p.clone(), *c))
        .collect();
    assert_eq!(got, want, "{what}");
}

#[test]
fn kostka_numbers_match_sage() {
    let mut n = 0;
    for (tag, arg, rest) in lines() {
        if tag != "kostka" {
            continue;
        }
        let (lam, mu) = pair(arg);
        let want: u128 = rest.trim().parse().expect("kostka value");
        assert_eq!(kostka(&lam, &mu), want, "K_{{{lam},{mu}}}");
        n += 1;
    }
    assert!(n > 100, "expected a real sweep, got {n}");
}

#[test]
fn characters_match_sage() {
    let mut n = 0;
    for (tag, arg, rest) in lines() {
        if tag != "char" {
            continue;
        }
        let (lam, mu) = pair(arg);
        let want: i128 = rest.trim().parse().expect("character value");
        assert_eq!(character(&lam, &mu), want, "chi^{lam}({mu})");
        n += 1;
    }
    assert!(n > 100, "expected a real sweep, got {n}");
}

#[test]
fn schur_products_match_sage() {
    let mut n = 0;
    for (tag, arg, rest) in lines() {
        if tag != "smul" {
            continue;
        }
        let (mu, nu) = pair(arg);
        let a: Schur<i64> = Schur::monomial(mu.clone(), 1);
        let b: Schur<i64> = Schur::monomial(nu.clone(), 1);
        assert_terms(&a.mul(&b), &parse_expansion(rest), &format!("s{mu}*s{nu}"));
        n += 1;
    }
    assert!(n > 50, "expected a real sweep, got {n}");
}

#[test]
fn integral_conversions_match_sage() {
    let mut n = 0;
    for (tag, arg, rest) in lines() {
        if !matches!(tag, "s2h" | "s2e" | "s2m") {
            continue;
        }
        let lam = parse_partition(arg);
        let s: Schur<i64> = Schur::monomial(lam.clone(), 1);
        let expected = parse_expansion(rest);
        match tag {
            "s2h" => assert_terms(
                &Homogeneous::from_schur(&s),
                &expected,
                &format!("h(s{lam})"),
            ),
            "s2e" => assert_terms(
                &Elementary::from_schur(&s),
                &expected,
                &format!("e(s{lam})"),
            ),
            "s2m" => assert_terms(&Monomial::from_schur(&s), &expected, &format!("m(s{lam})")),
            _ => continue,
        }
        n += 1;
    }
    assert!(n > 30, "expected a real sweep, got {n}");
}

#[test]
fn power_sum_conversion_matches_sage() {
    let mut n = 0;
    for (tag, arg, rest) in lines() {
        if tag != "s2p" {
            continue;
        }
        let lam = parse_partition(arg);
        let s: Schur<Rational> = Schur::monomial(lam.clone(), Rational::one());
        let got: PowerSum<Rational> = PowerSum::from_schur(&s);

        let want: BTreeMap<Partition, Rational> = parse_expansion(rest)
            .into_iter()
            .map(|(p, (num, den))| (p, Rational::new(num, den)))
            .collect();
        let actual: BTreeMap<Partition, Rational> =
            got.terms().iter().map(|(p, c)| (p.clone(), *c)).collect();
        assert_eq!(actual, want, "p(s{lam})");
        n += 1;
    }
    assert!(n > 10, "expected a real sweep, got {n}");
}

#[test]
fn skew_schur_matches_sage() {
    let mut n = 0;
    for (tag, arg, rest) in lines() {
        if tag != "skew" {
            continue;
        }
        let (lam, mu) = pair(arg);
        let sk: Schur<i64> = skew_schur(&lam, &mu);
        assert_terms(&sk, &parse_expansion(rest), &format!("s_{{{lam}/{mu}}}"));
        n += 1;
    }
    assert!(n > 20, "expected a real sweep, got {n}");
}

#[test]
fn plethysm_matches_sage() {
    use symfn::plethysm;
    let mut n = 0;
    for (tag, arg, rest) in lines() {
        if tag != "pleth" {
            continue;
        }
        let (f, g) = pair(arg);
        let sf: Schur<Rational> = Schur::monomial(f.clone(), Rational::one());
        let sg: Schur<Rational> = Schur::monomial(g.clone(), Rational::one());
        let got = plethysm(&sf, &sg);

        let want: BTreeMap<Partition, Rational> = parse_expansion(rest)
            .into_iter()
            .map(|(p, (num, den))| (p, Rational::new(num, den)))
            .collect();
        let actual: BTreeMap<Partition, Rational> =
            got.terms().iter().map(|(p, c)| (p.clone(), *c)).collect();
        assert_eq!(actual, want, "s{f}[s{g}]");
        n += 1;
    }
    assert!(n >= 20, "expected a real sweep, got {n}");
}

// --- Jack -------------------------------------------------------------------

/// Parse `NUM|DEN`, each a dense comma-separated coefficient list in α.
fn parse_ratfun(s: &str) -> (Vec<i128>, Vec<i128>) {
    let (num, den) = s.split_once('|').expect("NUM|DEN");
    let list = |x: &str| -> Vec<i128> {
        x.split(',')
            .map(|v| v.parse::<i128>().expect("coeff"))
            .collect()
    };
    (list(num), list(den))
}

/// Evaluate a dense integer polynomial in α at a rational point.
fn eval_dense(c: &[i128], x: Rational) -> Rational {
    let mut acc = Rational::zero();
    for v in c.iter().rev() {
        acc = acc.mul(&x);
        acc.add_assign(&Rational::from_int(*v));
    }
    acc
}

/// Jack `P`, `J` in the monomial basis and `J` in the power-sum basis, against
/// Sage.
///
/// Compared by **evaluating both sides at several α**, not by comparing
/// representations. Sage returns a reduced `num/den` over ℚ(α) while `AFrac`
/// keeps its denominator factored into primitive linear atoms with a separate
/// integer scalar; those are different normal forms for the same element, and
/// a structural comparison would fail on agreement. Three generic points are
/// enough: two degree-≤ 20 rational functions agreeing at 3 points where
/// neither has a pole is not a coincidence at these sizes, and the exact
/// symbolic comparison is `scripts/check_jack.py`'s job.
///
/// This is the *offline* half of the Jack oracle — it needs no Sage, so it runs
/// on every `cargo test` rather than when someone remembers.
#[test]
fn jack_expansions_match_sage() {
    use symfn::afrac::AFrac;

    let points = [
        Rational::from_int(3),
        Rational::from_int(7),
        Rational::new(1, 2),
    ];
    let mut checked = 0usize;
    for (tag, arg, rest) in lines() {
        let want_powersum = match tag {
            "jackp" | "jackj" => false,
            "jackjp" => true,
            _ => continue,
        };
        let lambda = parse_partition(arg);
        let got: BTreeMap<Partition, AFrac<Rational>> = if want_powersum {
            let f: PowerSum<AFrac<Rational>> = symfn::jack_j_powersum(&lambda);
            f.terms().clone()
        } else if tag == "jackp" {
            let f: Monomial<AFrac<Rational>> = symfn::jack_p(&lambda);
            f.terms().clone()
        } else {
            let f: Monomial<AFrac<Rational>> = symfn::jack_j(&lambda);
            f.terms().clone()
        };

        let mut seen = 0usize;
        for tok in rest.split_whitespace() {
            let (part, val) = tok.rsplit_once(':').expect("PART:NUM|DEN");
            let mu = parse_partition(part);
            let (num, den) = parse_ratfun(val);
            let ours = got
                .get(&mu)
                .unwrap_or_else(|| panic!("{tag} {lambda}: missing {mu}"));
            for &x in &points {
                let want = symfn::coeff::Field::div(&eval_dense(&num, x), &eval_dense(&den, x));
                let mine = ours.eval(&x).expect("no pole at a generic alpha");
                assert_eq!(mine, want, "{tag} {lambda} at {mu}, alpha = {x:?}");
            }
            seen += 1;
            checked += 1;
        }
        assert_eq!(
            seen,
            got.len(),
            "{tag} {lambda}: term count differs from Sage"
        );
    }
    assert!(
        checked > 700,
        "the Jack fixture must be non-trivial, got {checked}"
    );
}

/// **The monomial functions in the three Jack bases** — the inverses of
/// `jackp` and `jackj`.
///
/// Sage solves the triangular system from its own `P`; `monomial_to_jack_p`
/// back-substitutes through symfn's own `jack_table`. Evaluated at three
/// generic α for the reason the forward sweep is: symfn keeps the denominator
/// as a multiset of linear forms and Sage returns it expanded, so a structural
/// comparison would fail on agreement.
///
/// ⚠️ All three normalizations, and **not** at `α = 1`, which is where the
/// forward convention pins live. `m_11` is `P_11` outright,
/// `[α(α+1)/2] Q_11` and `[1/2] J_11`, and the first two are both 1 at α = 1 —
/// so α = 1 separates neither the normalizations nor the `α → 1/α` twist,
/// which fixes it (`docs/record/jack.md`).
#[test]
fn monomial_in_jack_matches_sage() {
    use symfn::afrac::AFrac;

    let points = [
        Rational::from_int(3),
        Rational::from_int(7),
        Rational::new(1, 2),
    ];
    let mut checked = 0usize;
    for (tag, arg, rest) in lines() {
        if !matches!(tag, "jminp" | "jminq" | "jminj") {
            continue;
        }
        let lambda = parse_partition(arg);
        let m: Monomial<AFrac<Rational>> =
            Monomial::monomial(lambda.clone(), <AFrac<Rational> as Ring>::one());
        let got = match tag {
            "jminp" => symfn::monomial_to_jack_p(&m),
            "jminq" => symfn::monomial_to_jack_q(&m),
            _ => symfn::monomial_to_jack_j(&m),
        };

        let mut seen = 0usize;
        for tok in rest.split_whitespace() {
            let (part, val) = tok.rsplit_once(':').expect("PART:NUM|DEN");
            let mu = parse_partition(part);
            let (num, den) = parse_ratfun(val);
            let ours = got
                .get(&mu)
                .unwrap_or_else(|| panic!("{tag} m_{lambda}: missing {mu}"));
            for &x in &points {
                let want = symfn::coeff::Field::div(&eval_dense(&num, x), &eval_dense(&den, x));
                let mine = ours.eval(&x).expect("no pole at a generic alpha");
                assert_eq!(mine, want, "{tag} m_{lambda} at {mu}, alpha = {x:?}");
            }
            seen += 1;
            checked += 1;
        }
        assert_eq!(
            seen,
            got.len(),
            "{tag} m_{lambda}: term count differs from Sage"
        );
    }
    assert!(checked > 300, "expected a real sweep, got {checked}");
}

// --- The (q,t) layer --------------------------------------------------------

/// Parse `QE.TE.COEFF;...`, or `Z` for the zero polynomial.
///
/// Strict, per [`docs/policies/validation.md`] V4: a malformed or non-integral
/// token is a parse failure rather than a wrong value the comparison absorbs.
fn qtpoly_terms(s: &str) -> Vec<(u32, u32, i128)> {
    if s == "Z" {
        return Vec::new();
    }
    s.split(';')
        .map(|tok| {
            let mut it = tok.split('.');
            let mut field = |what: &str| {
                it.next()
                    .unwrap_or_else(|| panic!("{tok}: missing {what}"))
                    .parse::<i128>()
                    .unwrap_or_else(|e| panic!("{tok}: {what}: {e}"))
            };
            let (a, b, c) = (
                field("q exponent"),
                field("t exponent"),
                field("coefficient"),
            );
            assert!(it.next().is_none(), "{tok}: trailing field");
            (
                u32::try_from(a).expect("q exponent fits u32"),
                u32::try_from(b).expect("t exponent fits u32"),
                c,
            )
        })
        .collect()
}

fn parse_qtpoly(s: &str) -> QtPoly<i64> {
    let mut out = <QtPoly<i64> as Ring>::zero();
    for (a, b, c) in qtpoly_terms(s) {
        out.add_term(a, b, i64::try_from(c).expect("coefficient fits i64"));
    }
    out
}

/// Evaluate a parsed `QE.TE.COEFF` list at a rational `(q, t)`.
fn eval_qtpoly(terms: &[(u32, u32, i128)], q: Rational, t: Rational) -> Rational {
    let mut acc = Rational::zero();
    for &(a, b, c) in terms {
        let mut term = Rational::from_int(c);
        for _ in 0..a {
            term = term.mul(&q);
        }
        for _ in 0..b {
            term = term.mul(&t);
        }
        acc.add_assign(&term);
    }
    acc
}

/// Parse `PART:QTPOLY ...` into the map a Schur expansion compares against.
fn parse_qt_expansion(rest: &str) -> BTreeMap<Partition, QtPoly<i64>> {
    rest.split_whitespace()
        .map(|tok| {
            let (part, poly) = tok.split_once(':').expect("PART:QTPOLY");
            (parse_partition(part), parse_qtpoly(poly))
        })
        .collect()
}

/// Sage lists only nonzero coefficients, so ours are pruned the same way before
/// the maps are compared.
fn nonzero<S: SymFn<QtPoly<i64>>>(f: &S) -> BTreeMap<Partition, QtPoly<i64>> {
    f.terms()
        .iter()
        .filter(|(_, c)| !c.is_empty())
        .map(|(p, c)| (p.clone(), c.clone()))
        .collect()
}

/// **`Q'_λ`, the modified Hall–Littlewood, in the Schur basis.**
///
/// ⚠️ Sage's `Qp()` — not `P()` and not `Q()`. The three differ by
/// `b_λ(t)` and by the transition matrix, and all three are plausible answers
/// to "the Hall–Littlewood polynomial", so `hlp` below is carried separately
/// rather than derived: a swap between them disagrees on a value here instead
/// of producing a self-consistent table.
#[test]
fn hall_littlewood_qp_matches_sage() {
    let mut n = 0;
    for (tag, arg, rest) in lines() {
        if tag != "hlqp" {
            continue;
        }
        let lam = parse_partition(arg);
        assert_eq!(
            nonzero(&hall_littlewood::<i64>(&lam)),
            parse_qt_expansion(rest),
            "Q'_{lam}"
        );
        n += 1;
    }
    assert!(n > 25, "expected a real sweep, got {n}");
}

/// **`P_λ(x; t)` in the Schur basis** — reached here by inverting the
/// Kostka–Foulkes matrix, so this checks the inversion as much as the
/// recursion feeding it.
#[test]
fn hall_littlewood_p_matches_sage() {
    let mut n = 0;
    for (tag, arg, rest) in lines() {
        if tag != "hlp" {
            continue;
        }
        let lam = parse_partition(arg);
        assert_eq!(
            nonzero(&hall_littlewood_p::<i64>(&lam)),
            parse_qt_expansion(rest),
            "P_{lam}"
        );
        n += 1;
    }
    assert!(n > 25, "expected a real sweep, got {n}");
}

/// **`P_μ · P_ν` and `Q'_μ · Q'_ν`, each in its own basis.**
///
/// Sage multiplies by coercing both operands into the Schur basis and
/// inverting the transition matrix back. symfn expands through its own forward
/// polynomials, multiplies with the Littlewood–Richardson backend, and
/// back-substitutes through `schur_to_hall_littlewood_p`. The two share the
/// definition of `P` and `Q'` and nothing about how the product is obtained.
///
/// ⚠️ **These structure constants are in `ℤ[t]`, not the `ℕ[t]` of the
/// classical Hall polynomials counting subgroups of abelian p-groups.** The
/// two differ by a normalization twist, and it is the negative coefficients
/// that tell them apart: `P_(1)² = P_(2) + (1 + t)·P_(1,1)` is common to every
/// convention in circulation, while `P_(2,1)²` has `1 + t − t³ − t⁴` at
/// `(3,1,1,1)`. The sweep asserts it saw a negative one, so a fixture that
/// somehow held only the agreeing values could not pass quietly.
#[test]
fn hall_littlewood_products_match_sage() {
    let mut n = 0;
    let mut negative = 0;
    for (tag, arg, rest) in lines() {
        let p_basis = match tag {
            "hlpmul" => true,
            "hlqpmul" => false,
            _ => continue,
        };
        let (mu, nu) = pair(arg);
        let (a, b): (Schur<QtPoly<i64>>, Schur<QtPoly<i64>>) = if p_basis {
            (hall_littlewood_p(&mu), hall_littlewood_p(&nu))
        } else {
            (hall_littlewood(&mu), hall_littlewood(&nu))
        };
        let product = a.mul(&b);
        let got = if p_basis {
            schur_to_hall_littlewood_p(&product)
        } else {
            schur_to_hall_littlewood_qp(&product)
        };
        let got: BTreeMap<Partition, QtPoly<i64>> =
            got.into_iter().filter(|(_, c)| !c.is_empty()).collect();
        negative += got
            .values()
            .flat_map(|c| c.terms())
            .filter(|(_, v)| *v < &0)
            .count();
        assert_eq!(got, parse_qt_expansion(rest), "{tag} {mu} * {nu}");
        n += 1;
    }
    assert!(n > 30, "expected a real sweep, got {n}");
    assert!(negative > 0, "the sweep never saw a negative coefficient");
}

/// **The Schur functions back in `P` and `Q'`** — the inverses of `hlp` and
/// `hlqp`.
///
/// Sage inverts the transition matrix; `schur_to_hall_littlewood_p` and `_qp`
/// back-substitute through symfn's own forward expansion. The two share the
/// family and nothing of how the inverse is obtained, so this is what holds
/// the inverse to something other than the expansion it came from — the round
/// trip in `src/hl.rs` cannot, being blind to any error the forward direction
/// shares.
///
/// ⚠️ Both normalizations. `s_2` reaches `t·P_11 + P_2` where `s_11` reaches
/// `Q'_11 − t·Q'_2`: the `t` lands on the smaller shape with a plus in one and
/// on the larger with a minus in the other, which is the pair that tells the
/// directions apart.
#[test]
fn schur_in_hall_littlewood_matches_sage() {
    let mut n = 0;
    for (tag, arg, rest) in lines() {
        let into_p = match tag {
            "sinhlp" => true,
            "sinhlqp" => false,
            _ => continue,
        };
        let lam = parse_partition(arg);
        let s: Schur<QtPoly<i64>> = Schur::monomial(lam.clone(), QtPoly::term(0, 0, 1));
        let got = if into_p {
            symfn::schur_to_hall_littlewood_p(&s)
        } else {
            symfn::schur_to_hall_littlewood_qp(&s)
        };
        assert_eq!(got, parse_qt_expansion(rest), "{tag} s_{lam}");
        n += 1;
    }
    assert!(n > 50, "expected a real sweep, got {n}");
}

/// **`K_{λμ}(t)`, every pair including the zeros.**
///
/// The zeros are the point: a transition that is right on its support and wrong
/// about where the support *is* passes a nonzero-only comparison.
#[test]
fn kostka_foulkes_matches_sage() {
    let (mut n, mut zeros) = (0, 0);
    for (tag, arg, rest) in lines() {
        if tag != "kf" {
            continue;
        }
        let (lam, mu) = pair(arg);
        let want = parse_qtpoly(rest.trim());
        if want.is_empty() {
            zeros += 1;
        }
        assert_eq!(kostka_foulkes::<i64>(&lam, &mu), want, "K_{lam}{mu}(t)");
        n += 1;
    }
    assert!(n > 150, "expected a real sweep, got {n}");
    assert!(zeros > 50, "the zeros must be in the sweep, got {zeros}");
}

/// **`K_{λμ}(q,t)`, every pair.**
///
/// The (q,t)-Kostka matrix has no zero entries, so the risk here is not the
/// support but the orientation: the two indices enter asymmetrically and a
/// transposed table is otherwise plausible. Sage has not computed these with
/// LLM since 2015 (`docs/record/qt-kostka.md`), so this is an oracle against a
/// route that shares no history with ours either.
#[test]
fn qt_kostka_matches_sage() {
    let mut n = 0;
    for (tag, arg, rest) in lines() {
        if tag != "qtk" {
            continue;
        }
        let (lam, mu) = pair(arg);
        assert_eq!(
            qt_kostka::<i64>(&lam, &mu),
            parse_qtpoly(rest.trim()),
            "K_{lam}{mu}(q,t)"
        );
        n += 1;
    }
    assert!(n > 70, "expected a real sweep, got {n}");
}

/// **`H̃_μ` in the Schur basis.**
///
/// ⚠️ The fixture is the convention pin: `H̃_{(2)} = s_2 + q·s_{11}` against
/// `H̃_{(11)} = s_2 + t·s_{11}` is the smallest pair that separates H̃ from H,
/// from J, and from a q ↔ t transpose — all of which agree on `H̃_{(1)}`, the
/// first case anyone checks.
#[test]
fn macdonald_htilde_matches_sage() {
    let mut n = 0;
    for (tag, arg, rest) in lines() {
        if tag != "macht" {
            continue;
        }
        let mu = parse_partition(arg);
        assert_eq!(
            nonzero(&macdonald_ht::<i64>(&mu)),
            parse_qt_expansion(rest),
            "H~_{mu}"
        );
        n += 1;
    }
    assert!(n > 25, "expected a real sweep, got {n}");
}

/// **`∇e_n` in the Schur basis.**
///
/// ∇ is the one Macdonald operator with an external oracle, and Δ_f, Δ'_f and
/// Θ_f are all tied back to it (`docs/record/macdonald-operators.md`) — so this
/// is the anchor those identity suites hang from.
#[test]
fn nabla_e_matches_sage() {
    let mut n = 0;
    for (tag, arg, rest) in lines() {
        if tag != "nablae" {
            continue;
        }
        let deg: u32 = arg.parse().expect("degree");
        assert_eq!(
            nonzero(&nabla_e::<i64>(deg)),
            parse_qt_expansion(rest),
            "nabla e_{deg}"
        );
        n += 1;
    }
    assert!(n > 5, "expected a real sweep, got {n}");
}

/// **`g^ν_{λμ}`, every triple including the zeros.**
///
/// The Kronecker product "rests entirely on p-basis diagonality plus s ↔ p, so
/// a wrong identity would be self-consistently wrong"
/// (`docs/record/kronecker.md`) — which is exactly the failure an in-tree
/// cross-route check cannot see. The zeros are more than half the sweep: the
/// support is the hard part here, not the values on it.
#[test]
fn kronecker_coefficients_match_sage() {
    let (mut n, mut zeros) = (0, 0);
    for (tag, arg, rest) in lines() {
        if tag != "kron" {
            continue;
        }
        let mut it = arg.split('|');
        let mut shape = |what: &str| parse_partition(it.next().unwrap_or_else(|| panic!("{what}")));
        let (lam, mu, nu) = (shape("lambda"), shape("mu"), shape("nu"));
        let want: i64 = rest.trim().parse().expect("kronecker coefficient");
        if want == 0 {
            zeros += 1;
        }
        let got: Rational = kronecker(&lam, &mu, &nu);
        assert_eq!(
            got,
            Rational::from_int(want.into()),
            "g^{nu}_{{{lam},{mu}}}"
        );
        n += 1;
    }
    assert!(n > 400, "expected a real sweep, got {n}");
    assert!(zeros > 200, "the zeros must be in the sweep, got {zeros}");
}

/// **Macdonald `P`, `Q` and `J` in the monomial basis.**
///
/// Compared by **evaluating both sides at generic (q,t)**, not structurally:
/// symfn keeps denominators factored into binomial atoms and Sage returns them
/// expanded, so `(1+q)(1−t)/(1−qt)` has two correct normal forms and a string
/// or term comparison would fail on agreement. The three points are chosen so
/// that `q^a·t^b = 1` only at `a = b = 0`, which is where every denominator
/// atom `1 − q^a t^b` has its pole.
///
/// ⚠️ All three normalizations are carried. `P`, `Q` and `J` differ by
/// `b_λ(q,t)` and `c_λ(q,t)`, and all three are called "the Macdonald
/// polynomial"; only `P` is monic, so a fixture holding one of them alone
/// would not catch a normalization swap.
#[test]
fn macdonald_expansions_match_sage() {
    use symfn::coeff::Field;
    use symfn::frac::Frac;

    // 2^a·3^b, 2^-a·5^b and 3^a·7^-b are all 1 only at a = b = 0.
    let points = [
        (Rational::from_int(2), Rational::from_int(3)),
        (Rational::new(1, 2), Rational::from_int(5)),
        (Rational::from_int(3), Rational::new(1, 7)),
    ];
    let mut checked = 0usize;
    for (tag, arg, rest) in lines() {
        if !matches!(tag, "macp" | "macq" | "macj") {
            continue;
        }
        let lam = parse_partition(arg);
        let got: BTreeMap<Partition, Frac<Rational>> = match tag {
            "macp" => symfn::macdonald_p::<Rational>(&lam).terms().clone(),
            "macq" => symfn::macdonald_q::<Rational>(&lam).terms().clone(),
            _ => symfn::macdonald_j::<Rational>(&lam).terms().clone(),
        };

        let mut seen = 0usize;
        for tok in rest.split_whitespace() {
            let (part, val) = tok.split_once(':').expect("PART:NUM|DEN");
            let mu = parse_partition(part);
            let (num, den) = val.split_once('|').expect("NUM|DEN");
            let (num, den) = (qtpoly_terms(num), qtpoly_terms(den));
            let ours = got
                .get(&mu)
                .unwrap_or_else(|| panic!("{tag} {lam}: missing {mu}"));
            for (q, t) in points {
                let want = Field::div(&eval_qtpoly(&num, q, t), &eval_qtpoly(&den, q, t));
                let mine = ours.eval(&q, &t).expect("no pole at a generic (q,t)");
                assert_eq!(mine, want, "{tag} {lam} at {mu}, (q,t) = ({q:?},{t:?})");
            }
            seen += 1;
            checked += 1;
        }
        assert_eq!(seen, got.len(), "{tag} {lam}: term count differs from Sage");
    }
    assert!(checked > 50, "expected a real sweep, got {checked}");
}

/// **The Schur functions in the Macdonald `J` basis** — the inverse of `macj`.
///
/// Sage reaches this matrix by a triangular solve over ℚ(q,t); `schur_in_j_table`
/// reads it off the `(q,t)`-Kostka table as a projection against the `(q,t)`
/// scalar product. The two share `J` and nothing of how the inverse is
/// obtained, which is what makes agreement evidence.
///
/// Compared by **cross-multiplying**, where the expansions above evaluate at a
/// generic point. Same problem — symfn keeps the denominator factored and Sage
/// returns it expanded — and here the point does not work: these denominators
/// are the hook products `c_μ c'_μ`, ten binomials at degree 5, and `2^a·3^b`
/// over that degree overflows the `i128` under `Rational` before any pole is
/// reached. `a·d = c·b` in `ℤ[q,t]` needs no point and no division.
///
/// The zero entries are dropped on both sides and the count is asserted, so a
/// route that filled the wrong triangle would fail on the shape before it
/// failed on a value.
#[test]
fn schur_in_macdonald_j_matches_sage() {
    let mut checked = 0usize;
    for (tag, arg, rest) in lines() {
        if tag != "sinj" {
            continue;
        }
        let lam = parse_partition(arg);
        let parts = symfn::partitions_of(lam.size());
        let i = parts
            .iter()
            .position(|p| p == &lam)
            .expect("lam is one of them");
        let row = &symfn::schur_in_j_table::<Rational>(lam.size())[i];

        let mut seen = 0usize;
        for tok in rest.split_whitespace() {
            let (part, val) = tok.split_once(':').expect("PART:NUM|DEN");
            let mu = parse_partition(part);
            let j = parts
                .iter()
                .position(|p| p == &mu)
                .expect("mu is one of them");
            let (num, den) = val.split_once('|').expect("NUM|DEN");
            let (num, den) = (qtpoly_of(&qtpoly_terms(num)), qtpoly_of(&qtpoly_terms(den)));
            let (mine_num, _) = row[j].parts();
            let mine_den = row[j].denominator();
            assert_eq!(mine_num.mul(&den), num.mul(&mine_den), "s_{lam} at J_{mu}");
            seen += 1;
            checked += 1;
        }
        let nonzero = row.iter().filter(|c| !c.is_zero()).count();
        assert_eq!(nonzero, seen, "s_{lam}: support differs from Sage");
    }
    assert!(checked > 30, "expected a real sweep, got {checked}");
}

/// **The Schur functions in the `H̃` basis** — the inverse of `macht`.
///
/// ⚠️ These denominators are products of `qᵃ − tᵇ`, not of `1 − qᵃtᵇ`, which is
/// why `schur_to_macdonald_ht` returns a [`Ratio`] over the wider atom family
/// rather than a `Frac`. The fixture hands the denominator over **expanded**,
/// so the comparison expands ours too and cross-multiplies; a generic point
/// would need one that is a pole of neither, and `q = t` is a pole of every
/// coefficient here.
///
/// Sage solves for this basis change itself; symfn factors it out of the Δ
/// operators' own coefficients, which is a different computation of the same
/// matrix (`docs/record/macdonald-operators.md`).
#[test]
fn schur_in_macdonald_ht_matches_sage() {
    use symfn::Ratio;

    let mut checked = 0usize;
    for (tag, arg, rest) in lines() {
        if tag != "sinht" {
            continue;
        }
        let lam = parse_partition(arg);
        let s: Schur<QtPoly<Rational>> =
            Schur::monomial(lam.clone(), QtPoly::term(0, 0, Rational::from_int(1)));
        let got: BTreeMap<Partition, Ratio<Rational>> = symfn::schur_to_macdonald_ht(&s);

        let mut seen = 0usize;
        for tok in rest.split_whitespace() {
            let (part, val) = tok.split_once(':').expect("PART:NUM|DEN");
            let mu = parse_partition(part);
            let (num, den) = val.split_once('|').expect("NUM|DEN");
            let (num, den) = (qtpoly_of(&qtpoly_terms(num)), qtpoly_of(&qtpoly_terms(den)));
            let ours = got
                .get(&mu)
                .unwrap_or_else(|| panic!("sinht s_{lam}: missing {mu}"));
            let (mine_num, atoms) = ours.parts();
            let mut mine_den = <QtPoly<Rational> as Ring>::one();
            for (&atom, &m) in atoms {
                for _ in 0..m {
                    mine_den = mine_den.mul(&atom.poly());
                }
            }
            assert_eq!(mine_num.mul(&den), num.mul(&mine_den), "s_{lam} at H~_{mu}");
            seen += 1;
            checked += 1;
        }
        assert_eq!(seen, got.len(), "s_{lam}: support differs from Sage");
    }
    assert!(checked > 50, "expected a real sweep, got {checked}");
}

/// **The monomial functions in Macdonald `P` and `Q`** — the inverses of `macp`
/// and `macq`.
///
/// Sage solves the triangular system from its own `P`; `monomial_to_macdonald_p`
/// back-substitutes through symfn's own `macdonald_p_table`. Compared by
/// cross-multiplying for `sinj`'s reason: symfn keeps the denominator factored
/// where Sage returns it expanded, and evaluating at a generic point overflows
/// the `i128` under `Rational` before a pole is reached.
///
/// ⚠️ Both normalizations. `m_11` is `P_11` outright where the `Q` coefficient
/// is `(1−qt)(1−q)/((1−t)(1−t²))` — the smallest shape at which the two
/// differ, so a fixture holding one alone would not catch a `b_λ` dropped or
/// applied twice.
#[test]
fn monomial_in_macdonald_matches_sage() {
    use symfn::frac::Frac;

    let mut checked = 0usize;
    for (tag, arg, rest) in lines() {
        if !matches!(tag, "minp" | "minq") {
            continue;
        }
        let lam = parse_partition(arg);
        let m: Monomial<Frac<Rational>> =
            Monomial::monomial(lam.clone(), <Frac<Rational> as Ring>::one());
        let got = if tag == "minp" {
            symfn::monomial_to_macdonald_p(&m)
        } else {
            symfn::monomial_to_macdonald_q(&m)
        };

        let mut seen = 0usize;
        for tok in rest.split_whitespace() {
            let (part, val) = tok.split_once(':').expect("PART:NUM|DEN");
            let mu = parse_partition(part);
            let (num, den) = val.split_once('|').expect("NUM|DEN");
            let (num, den) = (qtpoly_of(&qtpoly_terms(num)), qtpoly_of(&qtpoly_terms(den)));
            let ours = got
                .get(&mu)
                .unwrap_or_else(|| panic!("{tag} m_{lam}: missing {mu}"));
            let (mine_num, _) = ours.parts();
            assert_eq!(
                mine_num.mul(&den),
                num.mul(&ours.denominator()),
                "{tag} m_{lam} at {mu}"
            );
            seen += 1;
            checked += 1;
        }
        assert_eq!(seen, got.len(), "{tag} m_{lam}: support differs from Sage");
    }
    assert!(checked > 50, "expected a real sweep, got {checked}");
}

fn qtpoly_of(terms: &[(u32, u32, i128)]) -> symfn::QtPoly<Rational> {
    let mut out = symfn::QtPoly::zero();
    for &(a, b, c) in terms {
        out.add_term(a, b, Rational::from_int(c));
    }
    out
}

/// **The three LLT ribbon dictionaries: `H^(k)`, `H̃^(k)` and `G̃^(k)`.**
///
/// ⚠️ Two conventions are pinned here at once. Four normalizations of `G̃`
/// circulate and agree on the easy cases, so all three dictionaries are
/// carried rather than derived from one another; and Sage names the LLT
/// parameter **t** where symfn grades these families in **q**, so the fixture
/// writes the exponent into the q slot and this test is what would fail if
/// either side moved it.
///
/// `k = 1` is in the sweep because `H^(1)` is the Schur function — the cheapest
/// place a spin/cospin swap shows.
#[test]
fn llt_dictionaries_match_sage() {
    use symfn::llt::{llt_gtilde, llt_h, llt_h_tilde};

    let mut counts = (0, 0, 0);
    for (tag, arg, rest) in lines() {
        if !matches!(tag, "lltspin" | "lltcospin" | "lltgtilde") {
            continue;
        }
        let (level, shape) = arg.split_once('|').expect("K|SHAPE");
        let k: u32 = level.parse().expect("level");
        let lam = parse_partition(shape);
        let want = parse_qt_expansion(rest);
        match tag {
            "lltspin" => {
                assert_eq!(nonzero(&llt_h::<i64>(&lam, k)), want, "H^({k})_{lam}");
                counts.0 += 1;
            }
            "lltcospin" => {
                assert_eq!(
                    nonzero(&llt_h_tilde::<i64>(&lam, k)),
                    want,
                    "H~^({k})_{lam}"
                );
                counts.1 += 1;
            }
            _ => {
                assert_eq!(nonzero(&llt_gtilde::<i64>(&lam, k)), want, "G~^({k})_{lam}");
                counts.2 += 1;
            }
        }
    }
    assert!(
        counts.0 > 30 && counts.1 > 30 && counts.2 > 100,
        "expected a real sweep of all three, got {counts:?}"
    );
}

/// **Schubert structure constants `c^w_{uv}`.**
///
/// Two things are checked, and the second is the one an expansion-only fixture
/// would miss. Every coefficient Sage lists must match; and for `u, v ∈ S_3`
/// every `w` Sage does *not* list must come back zero, swept over the `S_M`
/// the fixture's `schubbound` record names. That bound is measured by the
/// generator rather than assumed here, because a zero-sweep over too small a
/// universe silently checks nothing.
#[test]
fn schubert_structure_constants_match_sage() {
    use std::collections::HashMap;
    use symfn::permutation::Perm;
    use symfn::schubert::schubert_coeff;

    fn one_line(s: &str) -> Perm {
        Perm::new(s.split(',').map(|x| x.parse::<u32>().expect("entry"))).expect("a permutation")
    }
    fn perms_of(n: usize) -> Vec<Vec<u32>> {
        fn rec(k: usize, cur: &mut Vec<u32>, out: &mut Vec<Vec<u32>>) {
            if k == cur.len() {
                out.push(cur.clone());
                return;
            }
            for i in k..cur.len() {
                cur.swap(k, i);
                rec(k + 1, cur, out);
                cur.swap(k, i);
            }
        }
        let (mut cur, mut out) = ((1..=n as u32).collect::<Vec<_>>(), Vec::new());
        rec(0, &mut cur, &mut out);
        out
    }

    let mut bounds: HashMap<usize, usize> = HashMap::new();
    for (tag, arg, rest) in lines() {
        if tag == "schubbound" {
            bounds.insert(
                arg.parse().expect("degree"),
                rest.trim().parse().expect("bound"),
            );
        }
    }
    let sweep_to = *bounds.get(&3).expect("the S_3 support bound");

    let (mut listed, mut swept) = (0, 0);
    for (tag, arg, rest) in lines() {
        if tag != "schub" {
            continue;
        }
        let (us, vs) = arg.split_once('|').expect("U|V");
        let (u, v) = (one_line(us), one_line(vs));

        let mut want: BTreeMap<Perm, i64> = BTreeMap::new();
        for tok in rest.split_whitespace() {
            let (w, c) = tok.rsplit_once(':').expect("W:COEFF");
            want.insert(one_line(w), c.parse().expect("coefficient"));
        }
        for (w, c) in &want {
            assert_eq!(schubert_coeff::<i64>(&u, &v, w), *c, "c^{w}_{{{u},{v}}}");
            listed += 1;
        }

        // The zeros, where the measured bound keeps the universe small.
        if us.split(',').count() == 3 && vs.split(',').count() == 3 {
            for line in perms_of(sweep_to) {
                let w = Perm::new(line.iter().copied()).expect("a permutation");
                if want.contains_key(&w) {
                    continue;
                }
                assert_eq!(
                    schubert_coeff::<i64>(&u, &v, &w),
                    0,
                    "c^{w}_{{{u},{v}}} must vanish"
                );
                swept += 1;
            }
        }
    }
    assert!(listed > 600, "expected a real sweep, got {listed}");
    assert!(swept > 3000, "the zeros must be swept, got {swept}");
}

/// **The Schubert scalar product, `∂_{w₀⁽ⁿ⁾}(S_u · S_v)`.**
///
/// The values come from Symmetrica through `SchubertPolynomial.scalar_product`,
/// which has no other backend, so this block is an external oracle whatever
/// else Sage dispatches here.
///
/// Two claims, and the second is what makes the fixture reach the adapter. The
/// expansion must match; and the rank the fixture records — Symmetrica's, read
/// off Sage's fixed-point-stripped one-line forms — must be the one the
/// adapter's rule produces, which is the longest support among the arguments.
/// The two disagree by one on the identity alone, where Sage keeps a length-1
/// word and symfn keeps nothing, and `∂_{w₀⁽¹⁾}` is empty either way.
#[test]
fn schubert_scalar_products_match_symmetrica_through_sage() {
    use symfn::permutation::Perm;
    use symfn::schubert::Schubert;

    fn one_line(s: &str) -> Perm {
        Perm::new(s.split(',').map(|x| x.parse::<u32>().expect("entry"))).expect("a permutation")
    }

    let mut checked = 0;
    for (tag, arg, rest) in lines() {
        if tag != "schubsp" {
            continue;
        }
        let (us, vs) = arg.split_once('|').expect("U|V");
        let (u, v) = (one_line(us), one_line(vs));
        let (rank, body) = rest.trim().split_once(' ').unwrap_or((rest.trim(), ""));
        let rank: u32 = rank.parse().expect("the rank");

        let n = u.support_len().max(v.support_len());
        assert_eq!(rank, n.max(1), "the rank Symmetrica used for {u}, {v}");

        let mut want: Schubert<i64> = Schubert::zero();
        for tok in body.split_whitespace() {
            let (w, c) = tok.rsplit_once(':').expect("W:COEFF");
            want.add_term(one_line(w), &c.parse::<i64>().expect("coefficient"));
        }
        let a: Schubert<i64> = Schubert::monomial(u, 1);
        let b: Schubert<i64> = Schubert::monomial(v, 1);
        assert_eq!(a.scalar_product(&b, n), want, "scalar product of {u}, {v}");
        checked += 1;
    }
    assert!(checked > 600, "expected a real sweep, got {checked}");
}

// --- The Hopf structure, and the specializations -----------------------------

/// **The coproduct `Δ(s_λ) = Σ_{μ⊆λ} s_μ ⊗ s_{λ/μ}`.**
///
/// The in-tree evidence for this is the Hopf axioms and agreement with the LR
/// route. Laws are convention-blind — every self-consistent normalization
/// satisfies them — so what the oracle adds is the values: which μ occur, and
/// with what multiplicity out of the skew expansion.
///
/// It does *not* pin which side of the tensor carries μ. Sym is cocommutative,
/// and every coproduct in this fixture is invariant under swapping the two
/// sides, so no value here could tell a transposed convention from this one.
/// That is a fact about the object rather than a gap in the sweep, and it is
/// recorded so a later reader does not mistake the sweep for evidence it
/// cannot carry.
#[test]
fn coproduct_matches_sage() {
    let mut n = 0;
    for (tag, arg, rest) in lines() {
        if tag != "cop" {
            continue;
        }
        let lam = parse_partition(arg);
        let want: BTreeMap<(Partition, Partition), i64> = rest
            .split_whitespace()
            .map(|tok| {
                let (pair, c) = tok.rsplit_once(':').expect("MU/NU:COEFF");
                let (mu, nu) = pair.split_once('/').expect("MU/NU");
                (
                    (parse_partition(mu), parse_partition(nu)),
                    c.parse().expect("coefficient"),
                )
            })
            .collect();
        let f: Schur<i64> = Schur::monomial(lam.clone(), 1);
        let got: BTreeMap<(Partition, Partition), i64> = coproduct(&f)
            .terms()
            .iter()
            .filter(|(_, c)| **c != 0)
            .map(|(k, c)| (k.clone(), *c))
            .collect();
        assert_eq!(got, want, "coproduct of s{lam}");
        n += 1;
    }
    assert!(n > 25, "expected a real sweep, got {n}");
}

/// **The antipode `S(s_λ) = (−1)^{|λ|} s_{λ'}`, and the counit `ε(s_λ) = δ_{λ,∅}`.**
///
/// ⚠️ The antipode couples a sign to a conjugation and both halves are silent
/// when wrong on a self-conjugate shape of even size, so the sweep runs over
/// whole degrees rather than hand-picked shapes. `S(s_{(2,1)}) = −s_{(2,1)}` is
/// the case that separates the sign from the conjugation: the shape is fixed by
/// conjugation, so only the sign is left to be wrong.
#[test]
fn antipode_and_counit_match_sage() {
    let (mut a, mut c) = (0, 0);
    for (tag, arg, rest) in lines() {
        if !matches!(tag, "anti" | "counit") {
            continue;
        }
        let lam = parse_partition(arg);
        let f: Schur<i64> = Schur::monomial(lam.clone(), 1);
        match tag {
            "anti" => {
                assert_terms(&antipode(&f), &parse_expansion(rest), &format!("S(s{lam})"));
                a += 1;
            }
            "counit" => {
                let want: i64 = rest.trim().parse().expect("counit value");
                assert_eq!(counit(&f), want, "counit of s{lam}");
                c += 1;
            }
            _ => continue,
        }
    }
    assert!(a > 25 && c > 25, "expected a real sweep, got {a} and {c}");
}

/// **`s_λ(1ⁿ)` and `s_λ(1, q, …, q^{n−1})`, over alphabets from 0 up.**
///
/// The alphabet size starts at 0, where `s_∅(1⁰) = 1` and every other shape
/// gives 0 — a convention over a well-posed question, so it is swept rather
/// than skipped. `ℓ(λ) > n` is the other edge, and the two agree that it
/// vanishes: `principal_specialization_q` returns no coefficients at all there,
/// which the fixture writes as `Z`.
#[test]
fn principal_specialization_matches_sage() {
    let (mut plain, mut graded, mut zeros) = (0, 0, 0);
    for (tag, arg, rest) in lines() {
        if !matches!(tag, "psp" | "pspq") {
            continue;
        }
        let (shape, size) = arg.split_once('|').expect("LAM|N");
        let lam = parse_partition(shape);
        let k: u32 = size.parse().expect("alphabet size");
        if tag == "psp" {
            let want: u128 = rest.trim().parse().expect("specialization value");
            assert_eq!(
                principal_specialization(&lam, k),
                Some(want),
                "s{lam}(1^{k})"
            );
            if want == 0 {
                zeros += 1;
            }
            plain += 1;
        } else {
            let body = rest.trim();
            let want: Vec<i128> = if body == "Z" {
                Vec::new()
            } else {
                body.split(',')
                    .map(|x| x.parse().expect("coefficient"))
                    .collect()
            };
            assert_eq!(
                principal_specialization_q(&lam, k),
                want,
                "s{lam}(1,q,..,q^{{{k}-1}})"
            );
            graded += 1;
        }
    }
    assert!(plain > 150 && graded > 150, "got {plain} and {graded}");
    assert!(
        zeros > 30,
        "the vanishing alphabets must be swept, got {zeros}"
    );
}

/// **`f^λ`, against a direct count of standard tableaux.**
///
/// Sage's side is `StandardTableaux(λ).cardinality()`, not its hook-length
/// formula: symfn computes `f^λ` by hooks, and an oracle using the same formula
/// would check the arithmetic and nothing else.
#[test]
fn dimension_matches_sage() {
    let mut n = 0;
    for (tag, arg, rest) in lines() {
        if tag != "dim" {
            continue;
        }
        let lam = parse_partition(arg);
        let want: u128 = rest.trim().parse().expect("dimension");
        assert_eq!(dimension(&lam), Some(want), "f^{lam}");
        n += 1;
    }
    assert!(n > 25, "expected a real sweep, got {n}");
}

/// **The reduced (stable) Kronecker coefficients `ḡ^ν_{λμ}`.**
///
/// Orellana–Zabrocki Theorem 7 makes an ordinary product in the `s̃` basis have
/// `ḡ` as its structure constants, so Sage's `st()` basis is a direct oracle
/// for [`reduced_kronecker`](symfn::reduced_kronecker). The in-tree evidence —
/// published expansions, the LR top degree, stability against the ordinary
/// Kronecker product — is real but contains no independent implementation of
/// `ḡ` itself.
///
/// The expansion is **inhomogeneous**, which is the point of the basis: terms
/// of every degree up to `|λ| + |μ|` appear, and a route that dropped the
/// lower-degree tail would still look like a plausible product. So the zeros
/// are swept too, over every ν the product could reach.
#[test]
fn reduced_kronecker_matches_sage() {
    use symfn::{partitions_of, reduced_kronecker};

    let (mut listed, mut swept) = (0, 0);
    for (tag, arg, rest) in lines() {
        if tag != "redkron" {
            continue;
        }
        let (lam, mu) = pair(arg);
        let want: BTreeMap<Partition, i64> = rest
            .split_whitespace()
            .map(|tok| {
                let (nu, c) = tok.rsplit_once(':').expect("NU:COEFF");
                (parse_partition(nu), c.parse().expect("coefficient"))
            })
            .collect();
        for (nu, c) in &want {
            assert_eq!(
                reduced_kronecker::<i64>(&lam, &mu, nu),
                *c,
                "gbar^{nu}_{{{lam},{mu}}}"
            );
            listed += 1;
        }
        for d in 0..=(lam.size() + mu.size()) {
            for nu in partitions_of(d) {
                if want.contains_key(&nu) {
                    continue;
                }
                assert_eq!(
                    reduced_kronecker::<i64>(&lam, &mu, &nu),
                    0,
                    "gbar^{nu}_{{{lam},{mu}}} must vanish"
                );
                swept += 1;
            }
        }
    }
    assert!(listed > 200, "expected a real sweep, got {listed}");
    assert!(swept > 200, "the zeros must be swept, got {swept}");
}
