//! Cross-validation against **Sage** as an independent oracle.
//!
//! The fixture is generated by `scripts/gen_sage_oracle.sage` (committed, so
//! these tests need no Sage installed) and contains values Sage computed with
//! its own algorithms: Kostka numbers as semistandard-tableau counts, symmetric
//! group characters, Schur products (hence every LR coefficient), the four
//! conversions out of the Schur basis, and skew Schur functions.
//!
//! Regenerate with:
//!   sage scripts/gen_sage_oracle.sage > tests/fixtures/sage_oracle.txt

use std::collections::BTreeMap;
use symfn::{
    character, kostka, skew_schur, Elementary, FromSchur, Homogeneous, Monomial, Partition,
    PowerSum, Rational, Ring, Schur, SymFn,
};

const FIXTURE: &str = include_str!("fixtures/sage_oracle.txt");

fn parse_partition(s: &str) -> Partition {
    if s.is_empty() {
        return Partition::default();
    }
    Partition::new(s.split(',').map(|x| x.parse::<u32>().expect("part")))
}

/// Parse `PART:COEFF ...` where COEFF is `n` or `n/d`.
fn parse_expansion(rest: &str) -> Vec<(Partition, (i128, i128))> {
    rest.split_whitespace()
        .map(|tok| {
            let (part, coeff) = tok.rsplit_once(':').expect("PART:COEFF");
            let c = match coeff.split_once('/') {
                Some((n, d)) => (n.parse().expect("num"), d.parse().expect("den")),
                None => (coeff.parse().expect("int"), 1),
            };
            (parse_partition(part), c)
        })
        .collect()
}

/// Iterate `(tag, arg, rest)` over fixture lines.
fn lines() -> impl Iterator<Item = (&'static str, &'static str, &'static str)> {
    FIXTURE.lines().filter(|l| !l.trim().is_empty()).map(|l| {
        let mut it = l.splitn(3, ' ');
        let tag = it.next().unwrap();
        let arg = it.next().unwrap_or("");
        let rest = it.next().unwrap_or("");
        (tag, arg, rest)
    })
}

fn pair(arg: &str) -> (Partition, Partition) {
    let (a, b) = arg.split_once('|').expect("LAM|MU");
    (parse_partition(a), parse_partition(b))
}

/// Compare an integral expansion against the oracle's expected terms.
fn assert_terms<S: SymFn<i64>>(actual: &S, expected: &[(Partition, (i128, i128))], what: &str) {
    let want: BTreeMap<Partition, i64> = expected
        .iter()
        .map(|(p, (n, d))| {
            assert_eq!(*d, 1, "{what}: expected integral coefficient");
            (p.clone(), *n as i64)
        })
        .collect();
    let got: BTreeMap<Partition, i64> = actual
        .terms()
        .iter()
        .map(|(p, c)| (p.clone(), *c))
        .collect();
    assert_eq!(got, want, "{what}");
}

#[test]
fn kostka_numbers_match_sage() {
    let mut n = 0;
    for (tag, arg, rest) in lines() {
        if tag != "kostka" {
            continue;
        }
        let (lam, mu) = pair(arg);
        let want: u128 = rest.trim().parse().expect("kostka value");
        assert_eq!(kostka(&lam, &mu), want, "K_{{{lam},{mu}}}");
        n += 1;
    }
    assert!(n > 100, "expected a real sweep, got {n}");
}

#[test]
fn characters_match_sage() {
    let mut n = 0;
    for (tag, arg, rest) in lines() {
        if tag != "char" {
            continue;
        }
        let (lam, mu) = pair(arg);
        let want: i128 = rest.trim().parse().expect("character value");
        assert_eq!(character(&lam, &mu), want, "chi^{lam}({mu})");
        n += 1;
    }
    assert!(n > 100, "expected a real sweep, got {n}");
}

#[test]
fn schur_products_match_sage() {
    let mut n = 0;
    for (tag, arg, rest) in lines() {
        if tag != "smul" {
            continue;
        }
        let (mu, nu) = pair(arg);
        let a: Schur<i64> = Schur::monomial(mu.clone(), 1);
        let b: Schur<i64> = Schur::monomial(nu.clone(), 1);
        assert_terms(&a.mul(&b), &parse_expansion(rest), &format!("s{mu}*s{nu}"));
        n += 1;
    }
    assert!(n > 50, "expected a real sweep, got {n}");
}

#[test]
fn integral_conversions_match_sage() {
    let mut n = 0;
    for (tag, arg, rest) in lines() {
        if !matches!(tag, "s2h" | "s2e" | "s2m") {
            continue;
        }
        let lam = parse_partition(arg);
        let s: Schur<i64> = Schur::monomial(lam.clone(), 1);
        let expected = parse_expansion(rest);
        match tag {
            "s2h" => assert_terms(
                &Homogeneous::from_schur(&s),
                &expected,
                &format!("h(s{lam})"),
            ),
            "s2e" => assert_terms(
                &Elementary::from_schur(&s),
                &expected,
                &format!("e(s{lam})"),
            ),
            "s2m" => assert_terms(&Monomial::from_schur(&s), &expected, &format!("m(s{lam})")),
            _ => continue,
        }
        n += 1;
    }
    assert!(n > 30, "expected a real sweep, got {n}");
}

#[test]
fn power_sum_conversion_matches_sage() {
    let mut n = 0;
    for (tag, arg, rest) in lines() {
        if tag != "s2p" {
            continue;
        }
        let lam = parse_partition(arg);
        let s: Schur<Rational> = Schur::monomial(lam.clone(), Rational::one());
        let got: PowerSum<Rational> = PowerSum::from_schur(&s);

        let want: BTreeMap<Partition, Rational> = parse_expansion(rest)
            .into_iter()
            .map(|(p, (num, den))| (p, Rational::new(num, den)))
            .collect();
        let actual: BTreeMap<Partition, Rational> =
            got.terms().iter().map(|(p, c)| (p.clone(), *c)).collect();
        assert_eq!(actual, want, "p(s{lam})");
        n += 1;
    }
    assert!(n > 10, "expected a real sweep, got {n}");
}

#[test]
fn skew_schur_matches_sage() {
    let mut n = 0;
    for (tag, arg, rest) in lines() {
        if tag != "skew" {
            continue;
        }
        let (lam, mu) = pair(arg);
        let sk: Schur<i64> = skew_schur(&lam, &mu);
        assert_terms(&sk, &parse_expansion(rest), &format!("s_{{{lam}/{mu}}}"));
        n += 1;
    }
    assert!(n > 20, "expected a real sweep, got {n}");
}

#[test]
fn plethysm_matches_sage() {
    use symfn::plethysm;
    let mut n = 0;
    for (tag, arg, rest) in lines() {
        if tag != "pleth" {
            continue;
        }
        let (f, g) = pair(arg);
        let sf: Schur<Rational> = Schur::monomial(f.clone(), Rational::one());
        let sg: Schur<Rational> = Schur::monomial(g.clone(), Rational::one());
        let got = plethysm(&sf, &sg);

        let want: BTreeMap<Partition, Rational> = parse_expansion(rest)
            .into_iter()
            .map(|(p, (num, den))| (p, Rational::new(num, den)))
            .collect();
        let actual: BTreeMap<Partition, Rational> =
            got.terms().iter().map(|(p, c)| (p.clone(), *c)).collect();
        assert_eq!(actual, want, "s{f}[s{g}]");
        n += 1;
    }
    assert!(n >= 20, "expected a real sweep, got {n}");
}

// --- Jack -------------------------------------------------------------------

/// Parse `NUM|DEN`, each a dense comma-separated coefficient list in α.
fn parse_ratfun(s: &str) -> (Vec<i128>, Vec<i128>) {
    let (num, den) = s.split_once('|').expect("NUM|DEN");
    let list = |x: &str| -> Vec<i128> {
        x.split(',')
            .map(|v| v.parse::<i128>().expect("coeff"))
            .collect()
    };
    (list(num), list(den))
}

/// Evaluate a dense integer polynomial in α at a rational point.
fn eval_dense(c: &[i128], x: Rational) -> Rational {
    let mut acc = Rational::zero();
    for v in c.iter().rev() {
        acc = acc.mul(&x);
        acc.add_assign(&Rational::from_int(*v));
    }
    acc
}

/// Jack `P`, `J` in the monomial basis and `J` in the power-sum basis, against
/// Sage.
///
/// Compared by **evaluating both sides at several α**, not by comparing
/// representations. Sage returns a reduced `num/den` over ℚ(α) while `AFrac`
/// keeps its denominator factored into primitive linear atoms with a separate
/// integer scalar; those are different normal forms for the same element, and
/// a structural comparison would fail on agreement. Three generic points are
/// enough: two degree-≤ 20 rational functions agreeing at 3 points where
/// neither has a pole is not a coincidence at these sizes, and the exact
/// symbolic comparison is `scripts/check_jack.py`'s job.
///
/// This is the *offline* half of the Jack oracle — it needs no Sage, so it runs
/// on every `cargo test` rather than when someone remembers.
#[test]
fn jack_expansions_match_sage() {
    use symfn::afrac::AFrac;

    let points = [
        Rational::from_int(3),
        Rational::from_int(7),
        Rational::new(1, 2),
    ];
    let mut checked = 0usize;
    for (tag, arg, rest) in lines() {
        let want_powersum = match tag {
            "jackp" | "jackj" => false,
            "jackjp" => true,
            _ => continue,
        };
        let lambda = parse_partition(arg);
        let got: BTreeMap<Partition, AFrac<Rational>> = if want_powersum {
            let f: PowerSum<AFrac<Rational>> = symfn::jack_j_powersum(&lambda);
            f.terms().clone()
        } else if tag == "jackp" {
            let f: Monomial<AFrac<Rational>> = symfn::jack_p(&lambda);
            f.terms().clone()
        } else {
            let f: Monomial<AFrac<Rational>> = symfn::jack_j(&lambda);
            f.terms().clone()
        };

        let mut seen = 0usize;
        for tok in rest.split_whitespace() {
            let (part, val) = tok.rsplit_once(':').expect("PART:NUM|DEN");
            let mu = parse_partition(part);
            let (num, den) = parse_ratfun(val);
            let ours = got
                .get(&mu)
                .unwrap_or_else(|| panic!("{tag} {lambda}: missing {mu}"));
            for &x in &points {
                let want = symfn::coeff::Field::div(&eval_dense(&num, x), &eval_dense(&den, x));
                let mine = ours.eval(&x).expect("no pole at a generic alpha");
                assert_eq!(mine, want, "{tag} {lambda} at {mu}, alpha = {x:?}");
            }
            seen += 1;
            checked += 1;
        }
        assert_eq!(
            seen,
            got.len(),
            "{tag} {lambda}: term count differs from Sage"
        );
    }
    assert!(
        checked > 700,
        "the Jack fixture must be non-trivial, got {checked}"
    );
}
